# config.py
# The Last of Us Survival Simulation - Game Constants

MAX_HP = 100
MAX_INVENTORY_CAP = 3

MEDKIT_HEAL_AMOUNT = 35

ZOMBIE_BASE_DMG = 2
ZOMBIE_MOLOTOV_DEFENSE = 2

CLICKER_PROBABILITY = 0.3
CLICKER_BASE_DMG = 3
CLICKER_MOLOTOV_DEFENSE = 2

BLOATER_SPAWN_STEPS = (60, 70, 80, 90, 100)
BLOATER_BASE_DMG = 30
BLOATER_MOLOTOV_DEFENSE = 5

TOTAL_STEPS = 100
